### ISSUE TITLE
GitHub tag / release v4.0.0

### ISSUE THREAD

**Issue by kachkaev** [js-fns/date-fns#3887]
👋 folks, congrats on v4 release! 🎉  TZ API looks amazing!

I opened the repo this morning and noticed this:
![Screenshot 2024-09-16 at 10 14 03](https://github.com/user-attachments/assets/de4d8f66-2017-43c4-83a8-d69dc12dad9a)

So my first thought was ‘v4 was still work-in-progress’. It’d be great if you could add an entry into https://github.com/date-fns/date-fns/releases, if that’s quick.

Cheers! 🙌

**Comment by Kikobeats** [comment]
This could be considered changelog https://blog.date-fns.org/v40-with-time-zone-support/ 😆

**Comment by kossnocorp** [comment]
Thank you for the heads up, done: https://github.com/date-fns/date-fns/releases/tag/v4.0.0
