### ISSUE TITLE
TypeError: format is not a function

### ISSUE THREAD

**Issue by RibbtDev** [js-fns/date-fns#927]
I am migrating from **moment** to **date-fns** and following docs on the official site. 

I have installed date-fns from npm and when I try to use I get this error:

**TypeError: format is not a function**

I have tried import, require but they all give same error. Also the **typeof(format)** returns **undefined**.

Using v1.29.0 on Nodejs

**Comment by kossnocorp** [comment]
Please provide the code snippet where you import and use the function.
