### ISSUE TITLE
formatDistance does not work properly (does not add "ago")

### ISSUE THREAD

**Issue by tomitrescak** [js-fns/date-fns#984]
Hi, the `formatDistance` does not work properly in `date-fns@next`. It does not add the english suffix/prefix

According to docs, following should produce `3 months ago` but produces only `3 months`

```
formatDistance(
  subDays(new Date(), 100),
  new Date()
)
```

See https://codesandbox.io/s/5kz75o6rmx

**Comment by ovvn** [comment]
@kossnocorp maybe it makes sense to have the `addSuffix` option set to true by default? It will make transition from moment.js easier.

**Comment by tomitrescak** [comment]
@ovvn I second that, although a breaking change I do not see many uses when you would not want to add suffix. But no biggie. I just created a helper.
